version: '3.5'

services:
  redis:
    container_name: redis
    image: bitnami/redis:7.0.9-debian-11-r5
    environment:
      REDIS__PASSWORD: ${REDIS__PASSWORD:-redis}
    ports:
      - "6381:6379"
    command: redis-server --requirepass $$REDIS__PASSWORD
    restart: unless-stopped
    volumes:
       - redis:/bitnami/redis/data
    networks:
      - docker_stack
    # network_mode: host
  
networks:
  docker_stack:
    external: true

volumes:
  redis:
