```
# nats.conf

# Client Port Configuration
port: 4222

# HTTP Monitoring Port
http_port: 8222

# Enforced Client Authentication
authorization {
  user: "app_client"
  password: "Abc12345"
}

# JetStream Engine Storage Setup
# jetstream {
#   store_dir: "/data"
# }

# Cluster Mesh Communication Setup
cluster {
  name: "NC-CLUSTER"
  listen: "0.0.0.0:6222"
  
  # Secure Route Credentials``
  authorization {
    user: "admin"
    password: "Abc12345"
  }
}
```