.PHONY: install-model

install-qwen3:
	# 32GB RAM, GPU
	ollama pull qwen2.5-coder:7b
	
install-qwen2.5:
	# 8GB to 16GB RAM
	# ollama pull qwen2.5-coder:7b
	docker exec -it ollama ollama run qwen2.5-coder:7b

install-deepseek-r1:
	deepseek-r1:14b
	